language: node_js
node_js:
- '0.10'
before_script:
  - cd Static
  - npm install
script:
  - gulp build
  - ls
  - cd ..
  - ls
deploy:
  provider: s3
  access_key_id: AKIAI2PMWXFL7WU5254A
  secret_access_key:
    secure: nfEpNnYDsA4xj1ycP159gkZ5JCj+Zl+ZaejYik6vYAfaAy4f370XccDtfh8Du/J7yElp50EG5X+qiDVhhtjKvBFKUYVgJmMOSzJ9baB2z+pI8vGaaV5ToBor8R1YtBHznPd41jY8Ahgvw2Rr/4gdLy2zq92fFW4pQdNXB/xyBz4=
  bucket: 'jhdm-com'
  endpoint: jhdm-com.s3-website.eu-central-1.amazonaws.com
  region: eu-central-1
  skip_cleanup: false
  local_dir: Static/Dist
  acl: public_read
  on:
    repo: johanhdm/johanhdm.com
